#!/usr/bin/env bash

if [ -L $0 ]
then SCRIPT_DIR=$(dirname $(readlink $0))
else SCRIPT_DIR=$(cd $(dirname $0); pwd)
fi

exec docker-compose \
  -f $SCRIPT_DIR/docker-compose.yml \
  run --rm \
  -v $(pwd):/pwd \
  -w /pwd \
  gcloud $*
