version: '3'
services:
  gcloud:
    image: google/cloud-sdk:alpine
    volumes:
      - ~/.config/gcloud:/.config/gcloud
      - ~/.ssh:/root/.ssh
    environment:
      - CLOUDSDK_CONFIG=/.config/gcloud
      - TERM=xterm-256color
      - USER
