version: '3'
services:
  gcloud:
    image: google/cloud-sdk
    volumes:
      - ./config:/root/.config/gcloud
      - ~/.ssh:/root/.ssh
    environment:
      - CLOUDSDK_CONFIG=/root/.config/gcloud
      - TERM=xterm-256color
      - USER
